CREATE TABLE COUNTRIES(
    ID int IDENTITY(1,1) PRIMARY KEY,
    Currency VARCHAR(4),
    CountryCode VARCHAR(8),
    CountryString VARCHAR(64)
);

CREATE TABLE INDICATORS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EventName VARCHAR(255) NOT NULL,
	Country INT FOREIGN KEY REFERENCES COUNTRIES(ID)
);

CREATE TABLE INDICATOR_VALUES(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IndicatorId INT FOREIGN KEY REFERENCES INDICATORS(ID) NOT NULL,
    Actual VARCHAR(8) NOT NULL,
    ReleaseDate DATE NOT NULL
);

--TODO: Create tables for bonds
CREATE TABLE BOND_TYPES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Country INT FOREIGN KEY REFERENCES COUNTRIES(ID),
	BondName VARCHAR(255) NOT NULL,
);

CREATE TABLE BOND_RATES(
    ID INT IDENTITY(1,1) PRIMARY KEY,
	TypeId INT FOREIGN KEY REFERENCES BOND_TYPES(ID),
	BondYield DECIMAL(18,6) NOT NULL,
	ConstantDate DATE NOT NULL,
);


----------------------------------------------------
CREATE TABLE TICKERS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Ticker VARCHAR(16),
);

CREATE TABLE GENERAL_STATS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TickerId INT FOREIGN KEY REFERENCES TICKERS(ID),
    IndicatorId INT FOREIGN KEY REFERENCES INDICATORS(ID),
    Name VARCHAR(32) NOT NULL,
    Value DECIMAL(18,3) NOT NULL,
    RollingDuration VARCHAR(16)
);

CREATE TABLE DESCRIPTIVE_STATS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TickerId INT FOREIGN KEY REFERENCES TICKERS(ID),
    Count INT,
    Mean DECIMAL(18,4),
    Std DECIMAL(18,4),
    Min DECIMAL(18,4),
    Max DECIMAL(18,4),
    Quartile1 DECIMAL(18,4),
    Quartile2 DECIMAL(18,4),
    Quartile3 DECIMAL(18,4)
);

CREATE TABLE HISTOGRAM(
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TickerId INT FOREIGN KEY REFERENCES TICKERS(ID),
  Counts INT(8,2),
  Bins DECIMAL(8,2) --Bin START value
);

/*
count    24208.000000
mean         0.000307
std          0.011952
min         -0.204669
25%         -0.004559
50%          0.000484
75%          0.005467
max          0.166096
*/