CREATE TABLE COUNTRIES(
    ID int IDENTITY(1,1) PRIMARY KEY,
    Currency VARCHAR(4) NOT NULL,
    CountryCode VARCHAR(8) NOT NULL,
    CountryString VARCHAR(64) NOT NULL
);

CREATE TABLE INDICATORS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EventName VARCHAR(255) NOT NULL,
	Country INT FOREIGN KEY REFERENCES COUNTRIES(ID) NOT NULL
);

CREATE TABLE INDICATOR_VALUES(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IndicatorId INT FOREIGN KEY REFERENCES INDICATORS(ID) NOT NULL,
    Actual VARCHAR(8) NOT NULL,
    ReleaseDate DATE NOT NULL
);

CREATE TABLE BOND_TYPES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Country INT FOREIGN KEY REFERENCES COUNTRIES(ID),
	BondName VARCHAR(255) NOT NULL,
);

CREATE TABLE BOND_RATES(
    ID INT IDENTITY(1,1) PRIMARY KEY,
	TypeId INT FOREIGN KEY REFERENCES BOND_TYPES(ID) NOT NULL,
	BondYield DECIMAL(18,6) NOT NULL,
	ConstantDate DATE NOT NULL,
);